//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntitiyF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public decimal Basic { get; set; }
        public int DepartmentsDepartId { get; set; }
    
        public virtual Departments Department { get; set; }
    }
}
